### ISSUE TITLE
URL for Brazil servers not working

### ISSUE THREAD

**Issue by fconteo17** [isaacKenyon/valorant-live-match-rank-grabber#4]
While trying to use the program in BR servers the api url needs to be different because br servers use the same url as the NA servers, but with the glz url you need the "br" in the url as well. I imagine the smaller regions use the same mechanic as there are only 4 urls: 

North America | https://pd.NA.a.pvp.net/
Europe | https://pd.EU.a.pvp.net/
Asia Pacific | https://pd.AP.a.pvp.net/
Korea | https://pd.KO.a.pvp.net/

The urls for the BR region would be:
glz_url = "https://glz-br-1.na.a.pvp.net"
pd_url = "https://pd.na.a.pvp.net"

**Comment by OwOHamper** [comment]
It should work now. Let me know if it works.
Thank you

**Comment by fconteo17** [comment]
It now works, thanks
